spring:
  application:
    name: Byzantine Simulation Engine

  datasource:
    url: jdbc:postgresql://localhost:5432/byzantine
    username: byzantine
    password: byzantine

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
