spring:
  application:
    name: Byzantine Simulation Engine

  # Desactivamos temporalmente la autoconfiguración de DataSource hasta que configuremos PostgreSQL
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
